### PR TITLE
Update Posion requirement to allow v5 & update deps in mix.lock

### PR DESCRIPTION
**Pull request by maennchen**

### CODE REVIEW

**Comment by jakelacey2012** [comment]
@bnchrch is there anything blocking you from updating poison and http_poison?

**Comment by bnchrch** [comment]
@jakelacey2012 absolutely none! I had just missed this completely. 

Thank you for the ping. 

Reviewing now.

**Review by bnchrch — APPROVED** [review]
Lgtm

 image

**Comment by jakelacey2012** [comment]
Nice, thanks for that <3

**Comment by bnchrch** [comment]
No thank you!

**Pull request merged**
